#!/usr/bin/env node
// Build static JSON dataset for oriz-org/rto-api.
// Source: https://en.wikipedia.org/wiki/List_of_Regional_Transport_Office_districts_in_India
// License: CC BY-SA 4.0 (data); MIT (code).

const STATE_NAMES = {
  AP: 'Andhra Pradesh',
  AR: 'Arunachal Pradesh',
  AS: 'Assam',
  BR: 'Bihar',
  CG: 'Chhattisgarh',
  CH: 'Chandigarh',
  DD: 'Dadra and Nagar Haveli and Daman and Diu',
  DL: 'Delhi',
  GA: 'Goa',
  GJ: 'Gujarat',
  HP: 'Himachal Pradesh',
  HR: 'Haryana',
  JH: 'Jharkhand',
  JK: 'Jammu and Kashmir',
  KA: 'Karnataka',
  KL: 'Kerala',
  LA: 'Ladakh',
  LD: 'Lakshadweep',
  MH: 'Maharashtra',
  ML: 'Meghalaya',
  MN: 'Manipur',
  MP: 'Madhya Pradesh',
  MZ: 'Mizoram',
  NL: 'Nagaland',
  OD: 'Odisha',
  PB: 'Punjab',
  PY: 'Puducherry',
  RJ: 'Rajasthan',
  SK: 'Sikkim',
  TG: 'Telangana',
  TN: 'Tamil Nadu',
  TR: 'Tripura',
  UK: 'Uttarakhand',
  UP: 'Uttar Pradesh',
  WB: 'West Bengal',
};

const RAW = {
  AP: {
    special: [
      {
        code: 'AP-39',
        office: 'RTA',
        districts: [
          'Tirupati district', 'Krishna district', 'NTR district', 'Vizianagaram district',
          'Visakhapatnam district', 'Alluri Sitharama Raju district', 'Anakapalli district',
          'Kakinada district', 'East Godavari district', 'Konaseema district', 'Eluru district',
          'West Godavari district', 'Palnadu district', 'Guntur district', 'Bapatla district',
          'Prakasam district', 'Sri Potti Sriramulu Nellore district', 'Kurnool district',
          'Nandyal district', 'Anantapur district', 'Sri Sathya Sai district', 'YSR district',
          'Annamayya district', 'Parvathipuram Manyam district', 'Srikakulam district',
          'Chittoor district',
        ],
        notes: 'One state-one code policy from Feb 2019. APSRTC vehicles use Z series; Police vehicles use P series.',
      },
      {
        code: 'AP-40',
        office: 'RTA',
        districts: ['Entire Andhra Pradesh'],
        notes: 'New series launched 2023 under one state-one code policy.',
      },
    ],
    older: [
      ['AP-02', '', 'Ananthapuramu District', 'Older series pre-2019'],
      ['AP-03', '', 'Chittoor District', 'Older series pre-2019'],
      ['AP-04', '', 'YSR Kadapa District', 'Older series pre-2019'],
      ['AP-05', 'Kakinada', 'East Godavari District', 'Older series pre-2019; RTO at former district HQ'],
      ['AP-07', '', 'Guntur district', 'Older series pre-2019'],
      ['AP-16', 'Vijayawada', 'Krishna District', 'Older series pre-2019; RTO at former district HQ'],
      ['AP-18', '', 'Andhra Pradesh Police', 'AP 18 P older series'],
      ['AP-21', '', 'Kurnool District', 'Older series pre-2019'],
      ['AP-26', '', 'Nellore District', 'Older series pre-2019'],
      ['AP-27', '', 'Prakasam District', 'Older series pre-2019'],
      ['AP-30', '', 'Srikakulam District', 'Older series pre-2019'],
      ['AP-31', '', 'Vishakhapatnam District', 'AP 32, AP 33, AP 34 also reserved for Vishakhapatnam'],
      ['AP-35', '', 'Vizianagaram District', 'Older series pre-2019'],
      ['AP-37', 'Eluru', 'West Godavari District', 'Older series pre-2019; RTO at former district HQ'],
    ],
  },
  AR: [
    ['AR-01', 'Itanagar', 'Papum Pare district'],
    ['AR-02', 'Itanagar', 'Papum Pare district'],
    ['AR-03', 'Tawang', 'Tawang district'],
    ['AR-04', 'Bomdila', 'West Kameng district'],
    ['AR-05', 'Seppa', 'East Kameng district'],
    ['AR-06', 'Ziro', 'Lower Subansiri district'],
    ['AR-07', 'Daporijo', 'Upper Subansiri district'],
    ['AR-08', 'Along', 'West Siang district'],
    ['AR-09', 'Pasighat', 'East Siang district'],
    ['AR-10', 'Anini', 'Dibang Valley district'],
    ['AR-11', 'Tezu', 'Lohit district'],
    ['AR-12', 'Changlang', 'Changlang district'],
    ['AR-13', 'Khonsa', 'Tirap district'],
    ['AR-14', 'Yingkiong', 'Upper Siang district'],
    ['AR-15', 'Koloriang', 'Kurung Kumey district'],
    ['AR-16', 'Roing', 'Dibang Valley district'],
    ['AR-17', 'Hawai', 'Anjaw district'],
    ['AR-19', 'Palin', 'Kra Daadi district'],
    ['AR-20', 'Namsai', 'Namsai district', 'Carved out from Lohit district on Nov 17, 2014'],
    ['AR-22', 'Siji', 'Lower Siang district', 'Carved out from West Siang district on Nov 24, 2018'],
  ],
  AS: [
    ['AS-01', 'Guwahati', 'Kamrup district'],
    ['AS-02', 'Nagaon', 'Nagaon district'],
    ['AS-03', 'Jorhat', 'Jorhat district'],
    ['AS-04', 'Sivasagar', 'Sivasagar district'],
    ['AS-05', 'Golaghat', 'Golaghat district'],
    ['AS-06', 'Dibrugarh', 'Dibrugarh district'],
    ['AS-07', 'Lakhimpur', 'Lakhimpur district'],
    ['AS-08', 'Haflong', 'Dima Hasao district'],
    ['AS-09', 'Karbi Anglong', 'Karbi Anglong district'],
    ['AS-10', 'Karimganj', 'Karimganj district'],
    ['AS-11', 'Silchar', 'Cachar district'],
    ['AS-12', 'Tezpur', 'Sonitpur district'],
    ['AS-13', 'Darrang', 'Darrang district'],
    ['AS-14', 'Nalbari', 'Nalbari district'],
    ['AS-15', 'Barpeta', 'Barpeta district'],
    ['AS-16', 'Kokrajhar', 'Kokrajhar district'],
    ['AS-17', 'Dhubri', 'Dhubri district'],
    ['AS-18', 'Goalpara', 'Goalpara district'],
    ['AS-19', 'Bongaigaon', 'Bongaigaon district'],
    ['AS-20', 'entire Assam State', 'entire Assam State', 'Vehicles of Assam State Transport Corporation'],
    ['AS-21', 'Morigaon', 'Morigaon district'],
    ['AS-22', 'Dhemaji', 'Dhemaji district'],
    ['AS-23', 'Tinsukia', 'Tinsukia district'],
    ['AS-24', 'Hailakandi', 'Hailakandi district'],
    ['AS-25', 'Kamrup', 'Kamrup district'],
    ['AS-26', 'Kajalgaon', 'Chirang district'],
    ['AS-27', 'Udalguri', 'Udalguri district'],
    ['AS-29', 'Majuli', 'Majuli district'],
    ['AS-30', 'Assam Police', 'Assam Police'],
    ['AS-31', 'Hojai', 'Hojai district'],
    ['AS-32', 'Biswanath Chariali', 'Biswanath district'],
    ['AS-33', 'Charaideo', 'Charaideo district'],
    ['AS-34', 'Hatsingimari', 'South Salmara-Mankachar district'],
  ],
  BR: [
    ['BR-01', 'Patna', 'Patna district'],
    ['BR-02', 'Gaya', 'Gaya district'],
    ['BR-03', 'Arrah', 'Bhojpur district'],
    ['BR-04', 'Chhapra', 'Saran district'],
    ['BR-05', 'Motihari', 'East Champaran district'],
    ['BR-06', 'Muzaffarpur', 'Muzaffarpur district'],
    ['BR-07', 'Darbhanga', 'Darbhanga district'],
    ['BR-08', 'Munger', 'Munger district'],
    ['BR-09', 'Begusarai', 'Begusarai district'],
    ['BR-10', 'Bhagalpur', 'Bhagalpur district'],
    ['BR-11', 'Purnia', 'Purnia district'],
    ['BR-19', 'Saharsa', 'Saharsa district'],
    ['BR-21', 'Bihar Sharif', 'Nalanda district'],
    ['BR-22', 'Bettiah', 'West Champaran district'],
    ['BR-24', 'Dehri', 'Rohtas district'],
    ['BR-25', 'Jehanabad', 'Jehanabad district'],
    ['BR-26', 'Aurangabad', 'Aurangabad district'],
    ['BR-27', 'Nawada', 'Nawada district'],
    ['BR-28', 'Gopalganj', 'Gopalganj district'],
    ['BR-29', 'Siwan', 'Siwan district'],
    ['BR-30', 'Sitamarhi', 'Sitamarhi district'],
    ['BR-31', 'Hajipur', 'Vaishali district'],
    ['BR-32', 'Madhubani', 'Madhubani district'],
    ['BR-33', 'Samastipur', 'Samastipur district'],
    ['BR-34', 'Khagaria', 'Khagaria district'],
    ['BR-37', 'Kishanganj', 'Kishanganj district'],
    ['BR-38', 'Araria', 'Araria district'],
    ['BR-39', 'Katihar', 'Katihar district'],
    ['BR-43', 'Madhepura', 'Madhepura district'],
    ['BR-44', 'Buxar', 'Buxar district'],
    ['BR-45', 'Bhabua', 'Kaimur district'],
    ['BR-46', 'Jamui', 'Jamui district'],
    ['BR-50', 'Supaul', 'Supaul district'],
    ['BR-51', 'Banka', 'Banka district'],
    ['BR-52', 'Sheikhpura', 'Sheikhpura district'],
    ['BR-53', 'Lakhisarai', 'Lakhisarai district'],
    ['BR-55', 'Sheohar', 'Sheohar district'],
    ['BR-56', 'Arwal', 'Arwal district'],
  ],
  CG: [
    ['CG-01', 'entire Chhattisgarh', 'entire Chhattisgarh', 'Governor of Chhattisgarh vehicles'],
    ['CG-02', 'entire Chhattisgarh', 'entire Chhattisgarh', 'Chhattisgarh Government vehicles'],
    ['CG-03', 'entire Chhattisgarh', 'entire Chhattisgarh', 'Chhattisgarh Police vehicles'],
    ['CG-04', 'Raipur', 'Raipur district'],
    ['CG-05', 'Dhamtari', 'Dhamtari district'],
    ['CG-06', 'Mahasamund', 'Mahasamund district'],
    ['CG-07', 'Durg', 'Durg district'],
    ['CG-08', 'Rajnandgaon', 'Rajnandgaon district'],
    ['CG-09', 'Kawardha', 'Kabirdham district'],
    ['CG-10', 'Bilaspur', 'Bilaspur district'],
    ['CG-11', 'Janjgir', 'Janjgir-Champa district'],
    ['CG-12', 'Korba', 'Korba district'],
    ['CG-13', 'Raigarh', 'Raigarh district'],
    ['CG-14', 'Jashpur Nagar', 'Jashpur district'],
    ['CG-15', 'Ambikapur', 'Surguja district'],
    ['CG-16', 'Baikunthpur', 'Koriya district'],
    ['CG-17', 'Jagdalpur', 'Bastar district'],
    ['CG-18', 'Dantewada', 'Dantewada district'],
    ['CG-19', 'Kanker', 'Kanker district'],
    ['CG-20', 'Bijapur', 'Bijapur district'],
    ['CG-21', 'Narayanpur', 'Narayanpur district'],
    ['CG-22', 'Baloda Bazar', 'Baloda Bazar district'],
    ['CG-23', 'Gariaband', 'Gariaband district'],
    ['CG-24', 'Balod', 'Balod district'],
    ['CG-25', 'Bemetara', 'Bemetara district'],
    ['CG-26', 'Sukma', 'Sukma district'],
    ['CG-27', 'Kondagaon', 'Kondagaon district'],
    ['CG-28', 'Mungeli', 'Mungeli district'],
    ['CG-29', 'Surajpur', 'Surajpur district'],
    ['CG-30', 'Balrampur', 'Balrampur district'],
  ],
  CH: [
    ['CH-01', 'Chandigarh', 'Chandigarh district'],
    ['CH-02', 'Chandigarh', 'Chandigarh district'],
    ['CH-03', 'Chandigarh', 'Chandigarh district'],
    ['CH-04', 'Chandigarh', 'Chandigarh district'],
  ],
  DD: [
    ['DD-01', 'Silvassa', 'Dadra and Nagar Haveli district', 'Previously DN-09, before the UT merger'],
    ['DD-02', 'Diu', 'Diu district'],
    ['DD-03', 'Daman', 'Daman district'],
  ],
  DL: [
    ['DL-1', 'Mall Road, Vishwavidyalaya', 'North Delhi District'],
    ['DL-2', 'Indraprastha Depot', 'New Delhi District'],
    ['DL-3', 'DDA Market, Sheikh Sarai', 'South Delhi District'],
    ['DL-4', 'Janakpuri', 'West Delhi District I'],
    ['DL-5', 'Loni Road, Shahdara', 'North East Delhi District'],
    ['DL-6', 'ISBT Sarai Kale Khan', 'Central Delhi District'],
    ['DL-7', 'DTC Depot, Mayur Vihar', 'East Delhi District-I'],
    ['DL-8', 'DTC Depot, Wazirpur', 'North West Delhi District-I'],
    ['DL-9', 'Sector-10, Dwarka', 'South West Delhi District-I'],
    ['DL-10', 'Raja Garden', 'West Delhi District-II'],
    ['DL-11', 'DTC Depot, Rohini', 'North West Delhi District-II'],
    ['DL-12', 'DTC Depot, Vasant Vihar', 'South West Delhi District-II'],
    ['DL-13', 'CBD Ground, Surajmal Vihar', 'East Delhi District-II'],
  ],
  GA: [
    ['GA-01', 'Panaji', 'North Goa district', 'Not in use'],
    ['GA-02', 'Margao', 'South Goa district', 'Not in use'],
    ['GA-03', 'Mapusa', 'Bardez taluka'],
    ['GA-04', 'Bicholim', 'Bicholim taluka, Sattari taluka'],
    ['GA-05', 'Ponda', 'Ponda taluka'],
    ['GA-06', 'Vasco da Gama', 'Mormugao taluka'],
    ['GA-07', 'Panaji', 'Tiswadi taluka'],
    ['GA-08', 'Margao', 'Salcette taluka'],
    ['GA-09', 'Quepem', 'Quepem taluka, Sanguem taluka'],
    ['GA-10', 'Canacona', 'Canacona taluka'],
    ['GA-11', 'Pernem', 'Pernem taluka'],
    ['GA-12', 'Dharbandora', 'Dharbandora taluka'],
  ],
  GJ: [
    ['GJ-01', 'Ahmedabad (West), Subhash Bridge', 'Western Ahmedabad District'],
    ['GJ-02', 'Mehsana', 'Mehsana District'],
    ['GJ-03', 'Rajkot', 'Rajkot District'],
    ['GJ-04', 'Bhavnagar', 'Bhavnagar District'],
    ['GJ-05', 'Surat', 'Western Surat District'],
    ['GJ-06', 'Vadodara', 'Vadodara District'],
    ['GJ-07', 'Nadiad', 'Kheda District'],
    ['GJ-08', 'Palanpur', 'Banaskantha District and Vav-Tharad District'],
    ['GJ-09', 'Himmatnagar', 'Sabarkantha District'],
    ['GJ-10', 'Jamnagar', 'Jamnagar District'],
    ['GJ-11', 'Junagadh', 'Junagadh District'],
    ['GJ-12', 'Bhuj', 'Western Kutch District'],
    ['GJ-13', 'Surendranagar', 'Surendranagar District'],
    ['GJ-14', 'Amreli', 'Amreli District'],
    ['GJ-15', 'Valsad', 'Valsad District'],
    ['GJ-16', 'Bharuch', 'Bharuch District'],
    ['GJ-17', 'Godhra', 'Panchmahal District'],
    ['GJ-18', 'Gandhinagar', 'Gandhinagar District', 'All GSRTC buses are registered here'],
    ['GJ-19', 'Bardoli', 'Eastern Surat District'],
    ['GJ-20', 'Dahod', 'Dahod District'],
    ['GJ-21', 'Navsari', 'Navsari District'],
    ['GJ-22', 'Rajpipla', 'Narmada District'],
    ['GJ-23', 'Anand', 'Anand District'],
    ['GJ-24', 'Patan', 'Patan District'],
    ['GJ-25', 'Porbandar', 'Porbandar District'],
    ['GJ-26', 'Vyara', 'Tapi District'],
    ['GJ-27', 'Ahmedabad (East), Vastral', 'Eastern Ahmedabad District'],
    ['GJ-28', 'Not Allocated', 'Reserved for Surat'],
    ['GJ-29', 'Not Allocated', 'Reserved for Vadodara'],
    ['GJ-30', 'Ahwa', 'Dang District'],
    ['GJ-31', 'Modasa', 'Aravalli District'],
    ['GJ-32', 'Veraval', 'Gir Somnath District'],
    ['GJ-33', 'Botad', 'Botad District'],
    ['GJ-34', 'Chhota Udaipur', 'Chhota Udaipur District'],
    ['GJ-35', 'Lunawada', 'Mahisagar District'],
    ['GJ-36', 'Morbi', 'Morbi District'],
    ['GJ-37', 'Khambhaliya', 'Devbhoomi Dwarka District'],
    ['GJ-38', 'Bavla', 'Rural Ahmedabad District'],
    ['GJ-39', 'Anjar', 'Eastern Kutch District'],
  ],
  HP: [
    ['HP-01', 'Statewide', 'Statewide', 'Tourist buses & Taxis'],
    ['HP-02', 'Statewide', 'Statewide', 'Tourist buses & Taxis'],
    ['HP-03', 'Shimla (Urban)', 'Shimla'],
    ['HP-04', 'Kangra, Dharamsala', 'Kangra'],
    ['HP-05', 'Mandi', 'Mandi'],
    ['HP-06', 'Rampur Bushahr', 'Shimla'],
    ['HP-07', 'Shimla (Urban)', 'Shimla'],
    ['HP-08', 'Chaupal', 'Shimla'],
    ['HP-09', 'Theog', 'Shimla'],
    ['HP-10', 'Rohru', 'Shimla'],
    ['HP-11', 'Arki', 'Solan'],
    ['HP-12', 'Nalagarh', 'Solan'],
    ['HP-13', 'Kandaghat', 'Solan'],
    ['HP-14', 'Solan', 'Solan'],
    ['HP-15', 'Parwanoo', 'Solan'],
    ['HP-16', 'Rajgarh', 'Sirmaur'],
    ['HP-17', 'Paonta Sahib', 'Sirmaur'],
    ['HP-18', 'Nahan', 'Sirmaur'],
    ['HP-19', 'Amb', 'Una'],
    ['HP-20', 'Una', 'Una'],
    ['HP-21', 'Barsar', 'Hamirpur'],
    ['HP-22', 'Hamirpur', 'Hamirpur'],
    ['HP-23', 'Ghumarwin', 'Bilaspur'],
    ['HP-24', 'Bilaspur', 'Bilaspur'],
    ['HP-25', 'Kalpa', 'Kinnaur'],
    ['HP-26', 'Nichar, Bhaba Nagar', 'Kinnaur'],
    ['HP-27', 'Pooh', 'Kinnaur'],
    ['HP-28', 'Sarkaghat', 'Mandi'],
    ['HP-29', 'Jogindernagar', 'Mandi'],
    ['HP-30', 'Karsog', 'Mandi'],
    ['HP-31', 'Sundernagar', 'Mandi'],
    ['HP-32', 'Gohar', 'Mandi'],
    ['HP-33', 'Mandi', 'Mandi'],
    ['HP-34', 'Kullu', 'Kullu'],
    ['HP-35', 'Anni', 'Kullu'],
    ['HP-36', 'Dehra', 'Kangra'],
    ['HP-37', 'Palampur', 'Kangra'],
    ['HP-38', 'Nurpur', 'Kangra'],
    ['HP-39', 'Dharamshala', 'Kangra'],
    ['HP-40', 'Kangra', 'Kangra'],
    ['HP-41', 'Kaza', 'Lahaul and Spiti'],
    ['HP-42', 'Keylong', 'Lahaul and Spiti'],
    ['HP-43', 'Udaipur', 'Lahaul and Spiti'],
    ['HP-44', 'Churah', 'Chamba'],
    ['HP-45', 'Pangi', 'Chamba'],
    ['HP-46', 'Bharmour', 'Chamba'],
    ['HP-47', 'Dalhousie', 'Chamba'],
    ['HP-48', 'Chamba', 'Chamba'],
    ['HP-49', 'Banjar', 'Kullu'],
    ['HP-50', 'Shimla', 'Shimla', 'Auto-rickshaws'],
    ['HP-51', 'Shimla (Rural)', 'Shimla'],
    ['HP-52', 'Shimla (Rural)', 'Shimla'],
    ['HP-53', 'Baijnath', 'Kangra'],
    ['HP-54', 'Jawali', 'Kangra'],
    ['HP-55', 'Nadaun', 'Hamirpur'],
    ['HP-56', 'Jaisinghpur', 'Kangra'],
    ['HP-57', 'Chowari', 'Chamba'],
    ['HP-58', 'Manali', 'Kullu'],
    ['HP-59', 'Solan', 'Solan'],
    ['HP-60', 'Hamirpur', 'Hamirpur'],
    ['HP-61', 'Kullu', 'Kullu'],
    ['HP-62', 'Shimla', 'Shimla'],
    ['HP-63', 'Shimla', 'Shimla'],
    ['HP-64', 'Solan', 'Solan'],
    ['HP-65', 'Mandi', 'Mandi'],
    ['HP-66', 'Kullu', 'Kullu'],
    ['HP-67', 'Hamirpur', 'Hamirpur'],
    ['HP-68', 'Kangra, Dharmsala', 'Kangra'],
    ['HP-69', 'Bilaspur', 'Bilaspur'],
    ['HP-70', 'Bilaspur', 'Bilaspur'],
    ['HP-71', 'Nahan', 'Sirmaur'],
    ['HP-72', 'Una', 'Una'],
    ['HP-73', 'Chamba', 'Chamba'],
    ['HP-74', 'Bhoranj', 'Hamirpur'],
    ['HP-75', 'Jubbal', 'Shimla'],
    ['HP-76', 'Paddhar', 'Mandi'],
    ['HP-77', 'Dodra Kawar', 'Shimla'],
    ['HP-78', 'Bangana', 'Una'],
    ['HP-79', 'Sangrah', 'Sirmaur'],
    ['HP-80', 'Haroli', 'Una'],
    ['HP-81', 'Salooni', 'Chamba'],
    ['HP-82', 'Balh', 'Mandi'],
    ['HP-83', 'Jawalaji', 'Kangra'],
    ['HP-84', 'Sujanpur Tihra', 'Hamirpur'],
    ['HP-85', 'Shillai', 'Sirmaur'],
    ['HP-86', 'Dharampur', 'Mandi'],
    ['HP-87', 'Janjehli', 'Mandi'],
    ['HP-88', 'Fatehpur', 'Kangra'],
    ['HP-89', 'Jhandutta', 'Bilaspur'],
    ['HP-90', 'Shahpur', 'Kangra'],
    ['HP-91', 'Naina Devi, Swarghat', 'Bilaspur'],
    ['HP-92', 'Rampur Bushahr', 'Shimla'],
    ['HP-93', 'Nalagarh', 'Solan'],
    ['HP-94', 'Nagrota Bagwan', 'Kangra'],
    ['HP-95', 'Kumarsain', 'Shimla'],
    ['HP-96', 'Dheera', 'Kangra'],
    ['HP-97', 'Indora', 'Kangra'],
    ['HP-98', 'Kasauli', 'Solan'],
    ['HP-99', 'Kotkhai', 'Shimla'],
  ],
  HR: [
    ['HR-01', 'Ambala', 'Ambala district'],
    ['HR-02', 'Jagadhari', 'Yamunanagar district'],
    ['HR-03', 'Panchkula', 'Panchkula district'],
    ['HR-04', 'Naraingarh', 'Ambala district'],
    ['HR-05', 'Karnal', 'Karnal district'],
    ['HR-06', 'Panipat', 'Panipat district'],
    ['HR-07', 'Thanesar', 'Kurukshetra district'],
    ['HR-08', 'Kaithal', 'Kaithal district'],
    ['HR-09', 'Guhla', 'Kaithal district'],
    ['HR-10', 'Sonipat', 'Sonipat district'],
    ['HR-11', 'Gohana', 'Sonipat district'],
    ['HR-12', 'Rohtak', 'Rohtak district'],
    ['HR-13', 'Bahadurgarh', 'Jhajjar district'],
    ['HR-14', 'Jhajjar', 'Jhajjar district'],
    ['HR-15', 'Meham', 'Rohtak district'],
    ['HR-16', 'Bhiwani', 'Bhiwani district'],
    ['HR-17', 'Siwani', 'Bhiwani district'],
    ['HR-18', 'Loharu', 'Bhiwani district'],
    ['HR-19', 'Charkhi Dadri', 'Charkhi Dadri district'],
    ['HR-20', 'Hisar', 'Hisar district'],
    ['HR-21', 'Hansi', 'Hisar district'],
    ['HR-22', 'Fatehabad', 'Fatehabad district'],
    ['HR-23', 'Tohana', 'Fatehabad district'],
    ['HR-24', 'Sirsa', 'Sirsa district'],
    ['HR-25', 'Mandi Dabwali', 'Sirsa district'],
    ['HR-26', 'Gurugram (North)', 'Gurugram district'],
    ['HR-27', 'Nuh', 'Mewat district'],
    ['HR-28', 'Ferozepur Jhirka', 'Mewat district'],
    ['HR-29', 'Ballabgarh', 'Faridabad district'],
    ['HR-30', 'Palwal', 'Palwal district'],
    ['HR-31', 'Jind', 'Jind district'],
    ['HR-32', 'Narwana', 'Jind district'],
    ['HR-33', 'Safidon', 'Jind district'],
    ['HR-34', 'Mahendragarh', 'Mahendragarh district'],
    ['HR-35', 'Narnaul', 'Mahendragarh district'],
    ['HR-36', 'Rewari', 'Rewari district'],
    ['HR-37', 'Ambala', 'Ambala district', 'Commercial vehicles only'],
    ['HR-38', 'Faridabad', 'Faridabad district', 'Commercial vehicles only'],
    ['HR-39', 'Hisar', 'Hisar district', 'Commercial vehicles only'],
    ['HR-40', 'Assandh', 'Karnal district'],
    ['HR-41', 'Pehowa', 'Kurukshetra district'],
    ['HR-42', 'Ganaur', 'Sonipat district'],
    ['HR-43', 'Kosli', 'Rewari district'],
    ['HR-44', 'Ellenabad', 'Sirsa district'],
    ['HR-45', 'Karnal', 'Karnal district', 'Commercial vehicles only'],
    ['HR-46', 'Rohtak', 'Rohtak district', 'Commercial vehicles only'],
    ['HR-47', 'Rewari', 'Rewari district', 'Commercial vehicles only'],
    ['HR-48', 'Tosham', 'Bhiwani district'],
    ['HR-49', 'Kalka', 'Panchkula district'],
    ['HR-50', 'Hodal', 'Palwal district'],
    ['HR-51', 'Faridabad (North)', 'Faridabad district'],
    ['HR-52', 'Hathin', 'Palwal district'],
    ['HR-53', 'Adampur', 'Hisar district'],
    ['HR-54', 'Barara', 'Ambala district'],
    ['HR-55', 'Gurugram', 'Gurugram district', 'Commercial vehicles only'],
    ['HR-56', 'Jind', 'Jind district', 'Commercial vehicles only'],
    ['HR-57', 'Sirsa', 'Sirsa district', 'Commercial vehicles only'],
    ['HR-58', 'Yamunanagar', 'Yamunanagar district', 'Commercial vehicles only'],
    ['HR-59', 'Ratia', 'Fatehabad district'],
    ['HR-60', 'Samalkha', 'Panipat district'],
    ['HR-61', 'Bhiwani', 'Bhiwani district', 'Commercial vehicles only'],
    ['HR-62', 'Fatehabad', 'Fatehabad district', 'Commercial vehicles only'],
    ['HR-63', 'Jhajjar', 'Jhajjar district', 'Commercial vehicles only'],
    ['HR-64', 'Kaithal', 'Kaithal district', 'Commercial vehicles only'],
    ['HR-65', 'Kurukshetra', 'Kurukshetra district', 'Commercial vehicles only'],
    ['HR-66', 'Narnaul', 'Mahendragarh district', 'Commercial vehicles only'],
    ['HR-67', 'Panipat', 'Panipat district', 'Commercial vehicles only'],
    ['HR-68', 'Panchkula', 'Panchkula district', 'Commercial vehicles only'],
    ['HR-69', 'Sonipat', 'Sonipat district', 'Commercial vehicles only'],
    ['HR-70', 'Chandigarh', 'Special series', 'Transport Commissioner reserved VIP/special demand numbers'],
    ['HR-71', 'Bilaspur', 'Yamunanagar district'],
    ['HR-72', 'Sohna', 'Gurugram district'],
    ['HR-73', 'Palwal', 'Palwal district', 'Commercial vehicles only'],
    ['HR-74', 'Nuh', 'Mewat district', 'Commercial vehicles only'],
    ['HR-75', 'Indri', 'Karnal district'],
    ['HR-76', 'Pataudi', 'Gurugram district'],
    ['HR-77', 'Beri', 'Jhajjar district'],
    ['HR-78', 'Shahabad Markanda', 'Kurukshetra district'],
    ['HR-79', 'Kharkhoda', 'Sonipat district'],
    ['HR-80', 'Barwala', 'Hisar district'],
    ['HR-81', 'Bawal', 'Rewari district'],
    ['HR-82', 'Kanina', 'Mahendragarh district'],
    ['HR-83', 'Kalayat', 'Kaithal district'],
    ['HR-84', 'Charkhi Dadri', 'Charkhi Dadri district', 'Commercial vehicles only'],
    ['HR-85', 'Ambala Cantt', 'Ambala district'],
    ['HR-86', 'Narnaund', 'Hisar district'],
    ['HR-87', 'Badkhal', 'Faridabad district'],
    ['HR-88', 'Badhra', 'Charkhi Dadri district'],
    ['HR-89', 'Badli', 'Jhajjar district'],
    ['HR-90', 'Uchana', 'Jind district'],
    ['HR-91', 'Gharaunda', 'Karnal district'],
    ['HR-92', 'Radaur', 'Yamunanagar district'],
    ['HR-93', 'Punhana', 'Mewat district'],
    ['HR-94', 'Kalanwali', 'Sirsa district'],
    ['HR-95', 'Sampla', 'Rohtak district'],
    ['HR-96', 'Taoru', 'Mewat district'],
    ['HR-97', 'Ladwa', 'Kurukshetra district'],
    ['HR-98', 'Badshahpur (Gurugram South)', 'Gurugram district'],
    ['HR-99', 'entire Haryana', 'entire Haryana', 'Temporary numbers for new vehicles'],
  ],
  JH: [
    ['JH-01', 'Ranchi', 'Ranchi district'],
    ['JH-02', 'Hazaribagh', 'Hazaribagh district'],
    ['JH-03', 'Daltonganj', 'Palamu district'],
    ['JH-04', 'Dumka', 'Dumka district'],
    ['JH-05', 'Jamshedpur', 'East Singhbhum district'],
    ['JH-06', 'Chaibasa', 'West Singhbhum district'],
    ['JH-07', 'Gumla', 'Gumla district'],
    ['JH-08', 'Lohardaga', 'Lohardaga district'],
    ['JH-09', 'Bokaro', 'Bokaro district'],
    ['JH-10', 'Dhanbad', 'Dhanbad district'],
    ['JH-11', 'Giridih', 'Giridih district'],
    ['JH-12', 'Koderma', 'Koderma district'],
    ['JH-13', 'Chatra', 'Chatra district'],
    ['JH-14', 'Garhwa', 'Garhwa district'],
    ['JH-15', 'Deoghar', 'Deoghar district'],
    ['JH-16', 'Pakur', 'Pakur district'],
    ['JH-17', 'Godda', 'Godda district'],
    ['JH-18', 'Sahibganj', 'Sahebganj district'],
    ['JH-19', 'Latehar', 'Latehar district'],
    ['JH-20', 'Simdega', 'Simdega district'],
    ['JH-21', 'Jamtara', 'Jamtara district'],
    ['JH-22', 'Seraikela Kharsawan', 'Seraikela Kharsawan district'],
    ['JH-23', 'Khunti', 'Khunti district'],
    ['JH-24', 'Ramgarh', 'Ramgarh district'],
  ],
  JK: [
    ['JK-01', 'Srinagar', 'Srinagar District'],
    ['JK-02', 'Jammu', 'Jammu District'],
    ['JK-03', 'Anantnag', 'Anantnag District'],
    ['JK-04', 'Budgam', 'Budgam District'],
    ['JK-05', 'Baramulla', 'Baramulla District'],
    ['JK-06', 'Doda', 'Doda District'],
    ['JK-08', 'Lakhanpur, Kathua', 'Kathua District'],
    ['JK-09', 'Kupwara', 'Kupwara District'],
    ['JK-11', 'Rajouri', 'Rajouri District'],
    ['JK-12', 'Poonch', 'Poonch district'],
    ['JK-13', 'Pulwama', 'Pulwama District'],
    ['JK-14', 'Udhampur', 'Udhampur District'],
    ['JK-15', 'Bandipora', 'Bandipora District'],
    ['JK-16', 'Ganderbal', 'Ganderbal District'],
    ['JK-17', 'Kishtwar', 'Kishtwar District'],
    ['JK-18', 'Kulgam', 'Kulgam District'],
    ['JK-19', 'Ramban', 'Ramban District'],
    ['JK-20', 'Reasi', 'Reasi District'],
    ['JK-21', 'Samba', 'Samba District'],
    ['JK-22', 'Shopian', 'Shopian District'],
  ],
};

module.exports = { STATE_NAMES, RAW };
