const KA = [
  ['KA-01', 'Bengaluru Central, HSR Layout', 'Bengaluru Urban District', 'Covers Central Bengaluru'],
  ['KA-02', 'Bengaluru West, Rajajinagar', 'Bengaluru Urban District', 'Covers Western Bengaluru'],
  ['KA-03', 'Bengaluru East, Kasturinagar', 'Bengaluru Urban District', 'Covers Eastern Bengaluru'],
  ['KA-04', 'Bengaluru North, Yeshwantpur', 'Bengaluru Urban District', 'Covers Northern Bengaluru'],
  ['KA-05', 'Bengaluru South, Jayaprakash Nagara', 'Bengaluru Urban District', 'Covers Southern Bengaluru'],
  ['KA-06', 'Tumakuru', 'Tumakuru District'],
  ['KA-07', 'Kolar', 'Kolar District'],
  ['KA-08', 'Kolar (KGF region)', 'Kolar District'],
  ['KA-09', 'Mysuru West', 'Mysuru District'],
  ['KA-10', 'Chamarajanagar', 'Chamarajanagara District'],
  ['KA-11', 'Mandya', 'Mandya District'],
  ['KA-12', 'Madikeri', 'Kodagu District'],
  ['KA-13', 'Hassan', 'Hassan District'],
  ['KA-14', 'Shivamogga', 'Shivamogga District'],
  ['KA-15', 'Sagara', 'Shivamogga District'],
  ['KA-16', 'Chitradurga', 'Chitradurga District'],
  ['KA-17', 'Davanagere', 'Davanagere District'],
  ['KA-18', 'Chikkamagaluru', 'Chikkamagaluru District'],
  ['KA-19', 'Mangaluru', 'Dakshina Kannada District'],
  ['KA-20', 'Udupi', 'Udupi District'],
  ['KA-21', 'Puttur', 'Dakshina Kannada District'],
  ['KA-22', 'Belagavi', 'Belagavi District'],
  ['KA-23', 'Chikkodi', 'Belagavi District'],
  ['KA-24', 'Bailhongal', 'Belagavi District'],
  ['KA-25', 'Dharwad', 'Dharwad District'],
  ['KA-26', 'Gadag', 'Gadag District'],
  ['KA-27', 'Haveri', 'Haveri District'],
  ['KA-28', 'Vijayapura', 'Vijayapura District'],
  ['KA-29', 'Bagalkote', 'Bagalkote District'],
  ['KA-30', 'Karwar', 'Uttara Kannada District'],
  ['KA-31', 'Sirsi', 'Uttara Kannada District'],
  ['KA-32', 'Kalaburagi', 'Kalaburagi District'],
  ['KA-33', 'Yadgir', 'Yadgir District'],
  ['KA-34', 'Ballari', 'Ballari District'],
  ['KA-35', 'Hosapete', 'Vijayanagara District'],
  ['KA-36', 'Raichur', 'Raichur District'],
  ['KA-37', 'Koppal', 'Koppal District'],
  ['KA-38', 'Bidar', 'Bidar District'],
  ['KA-39', 'Bhalki', 'Bidar District'],
  ['KA-40', 'Chikkaballapura', 'Chikkaballapura District'],
  ['KA-41', 'Jnana Bharathi', 'Bengaluru Urban District', 'Covers Greater Bengaluru western suburbs'],
  ['KA-42', 'Ramanagara', 'Ramanagara District'],
  ['KA-43', 'Devanahalli', 'Bengaluru Rural District'],
  ['KA-44', 'Tiptur', 'Tumakuru District'],
  ['KA-45', 'Hunsur', 'Mysuru District'],
  ['KA-46', 'Sakleshpura', 'Hassan District'],
  ['KA-47', 'Honnavar', 'Uttara Kannada District'],
  ['KA-48', 'Jamkhandi', 'Bagalkote District'],
  ['KA-49', 'Gokak', 'Belagavi District'],
  ['KA-50', 'Yelahanka, Bengaluru', 'Bengaluru Urban District', 'Covers Bengaluru northern suburbs'],
  ['KA-51', 'Electronic City, Bengaluru', 'Bengaluru Urban District', 'Covers Bengaluru southern suburbs'],
  ['KA-52', 'Nelamangala', 'Bengaluru Rural District'],
  ['KA-53', 'Krishnarajapuram, Bengaluru', 'Bengaluru Urban District', 'Covers Bengaluru eastern suburbs and Hoskote Taluk'],
  ['KA-54', 'Nagamangala', 'Mandya District'],
  ['KA-55', 'Mysuru East', 'Mysuru District'],
  ['KA-56', 'Basavakalyan', 'Bidar District'],
  ['KA-57', 'Shantinagara', 'Bengaluru Urban District', 'KA-57 F series exclusively for KSRTC and BMTC buses'],
  ['KA-59', 'Chandapura', 'Bengaluru Urban District', 'Covers Anekal Taluk'],
  ['KA-63', 'Dharwad East', 'Dharwad District'],
  ['KA-64', 'Madhugiri', 'Tumakuru District'],
  ['KA-65', 'Dandeli', 'Uttara Kannada District'],
  ['KA-66', 'Tarikere', 'Chikkamagaluru District'],
  ['KA-67', 'Chintamani', 'Chikkaballapura District'],
  ['KA-68', 'Ranebennur', 'Haveri District'],
  ['KA-69', 'Ramdurg', 'Belagavi District'],
  ['KA-70', 'Bantwal', 'Dakshina Kannada District'],
  ['KA-71', 'Athani', 'Belagavi District'],
];

const KL = [
  ['KL-01', 'Thiruvananthapuram', 'Thiruvananthapuram Corporation', 'Most Kerala Government vehicles including Police are registered here'],
  ['KL-02', 'Kollam', 'Kollam Municipal Corporation'],
  ['KL-03', 'Pathanamthitta', 'Pathanamthitta'],
  ['KL-04', 'Alappuzha', 'Alappuzha'],
  ['KL-05', 'Kottayam', 'Kottayam'],
  ['KL-06', 'Idukki', 'Idukki, Painavu'],
  ['KL-07', 'Kochi', 'Ernakulam District', 'Covers parts of Greater Kochi'],
  ['KL-08', 'Thrissur', 'Thrissur Corporation'],
  ['KL-09', 'Palakkad', 'Palakkad'],
  ['KL-10', 'Malappuram', 'Malappuram'],
  ['KL-11', 'Kozhikode', 'Kozhikode Municipal Corporation'],
  ['KL-12', 'Kalpetta', 'Wayanad District'],
  ['KL-13', 'Kannur', 'Kannur Municipal Corporation'],
  ['KL-14', 'Kasaragod', 'Kasaragod'],
  ['KL-15', 'Nationalised Sector I, Thiruvananthapuram', 'Thiruvananthapuram', 'Exclusively for KSRTC and KURTC buses'],
  ['KL-16', 'Attingal', 'Thiruvananthapuram District'],
  ['KL-17', 'Muvattupuzha', 'Ernakulam District'],
  ['KL-18', 'Vadakara', 'Kozhikode District'],
  ['KL-19', 'Parassala', 'Thiruvananthapuram District'],
  ['KL-20', 'Neyyattinkara', 'Thiruvananthapuram District'],
  ['KL-21', 'Nedumangad', 'Thiruvananthapuram District'],
  ['KL-22', 'Kazhakkoottam', 'Thiruvananthapuram'],
  ['KL-23', 'Karunagappalli', 'Kollam District'],
  ['KL-24', 'Kottarakkara', 'Kollam District'],
  ['KL-25', 'Punalur', 'Kollam District'],
  ['KL-26', 'Adoor', 'Pathanamthitta District'],
  ['KL-27', 'Tiruvalla', 'Pathanamthitta District'],
  ['KL-28', 'Mallappally', 'Pathanamthitta District'],
  ['KL-29', 'Kayamkulam', 'Alappuzha District'],
  ['KL-30', 'Chengannur', 'Alappuzha District'],
  ['KL-31', 'Mavelikkara', 'Alappuzha District'],
  ['KL-32', 'Cherthala', 'Alappuzha District'],
  ['KL-33', 'Changanassery', 'Kottayam District'],
  ['KL-34', 'Kanjirapalli', 'Kottayam District'],
  ['KL-35', 'Pala', 'Kottayam District'],
  ['KL-36', 'Vaikom', 'Kottayam District'],
  ['KL-37', 'Vandiperiyar', 'Idukki District'],
  ['KL-38', 'Thodupuzha', 'Idukki District'],
  ['KL-39', 'Thripunithura', 'Ernakulam District'],
  ['KL-40', 'Perumbavoor', 'Ernakulam District'],
  ['KL-41', 'Aluva', 'Ernakulam District'],
  ['KL-42', 'North Paravur', 'Ernakulam District'],
  ['KL-43', 'Fort Kochi & Mattancherry', 'Ernakulam District'],
  ['KL-44', 'Kothamangalam', 'Ernakulam District'],
  ['KL-45', 'Irinjalakuda', 'Thrissur District'],
  ['KL-46', 'Guruvayur', 'Thrissur District'],
  ['KL-47', 'Kodungallur', 'Thrissur District'],
  ['KL-48', 'Wadakkancherry', 'Thrissur District'],
  ['KL-49', 'Alathur', 'Palakkad District'],
  ['KL-50', 'Mannarkkad', 'Palakkad District'],
  ['KL-51', 'Ottapalam', 'Palakkad District'],
  ['KL-52', 'Pattambi', 'Palakkad District'],
  ['KL-53', 'Perinthalmanna', 'Malappuram District'],
  ['KL-54', 'Ponnani', 'Malappuram District'],
  ['KL-55', 'Tirur', 'Malappuram District'],
  ['KL-56', 'Koyilandy', 'Kozhikode District'],
  ['KL-57', 'Koduvally', 'Kozhikode District'],
  ['KL-58', 'Thalassery', 'Kannur District'],
  ['KL-59', 'Taliparamba', 'Kannur District'],
  ['KL-60', 'Kanhangad', 'Kasargod District'],
  ['KL-61', 'Kunnathur', 'Kollam District'],
  ['KL-62', 'Ranni', 'Pathanamthitta District'],
  ['KL-63', 'Angamaly', 'Ernakulam District'],
  ['KL-64', 'Chalakkudy', 'Thrissur District'],
  ['KL-65', 'Tirurangadi', 'Malappuram District'],
  ['KL-66', 'Kuttanad', 'Alappuzha District'],
  ['KL-67', 'Uzhavoor', 'Kottayam District'],
  ['KL-68', 'Devikulam', 'Idukki District'],
  ['KL-69', 'Udumbanchola', 'Idukki District'],
  ['KL-70', 'Chittur', 'Palakkad District'],
  ['KL-71', 'Nilambur', 'Malappuram District'],
  ['KL-72', 'Mananthavady', 'Wayanad District'],
  ['KL-73', 'Sulthan Bathery', 'Wayanad District'],
  ['KL-74', 'Kattakada', 'Thiruvananthapuram District'],
  ['KL-75', 'Thriprayar', 'Thrissur District'],
  ['KL-76', 'Nanmanda', 'Kozhikode District'],
  ['KL-77', 'Perambra', 'Kozhikode District'],
  ['KL-78', 'Iritty', 'Kannur District'],
  ['KL-79', 'Vellarikundu', 'Kasargod District'],
  ['KL-80', 'Pathanapuram', 'Kollam District'],
  ['KL-81', 'Varkala', 'Thiruvananthapuram District'],
  ['KL-82', 'Chadayamangalam', 'Kollam District'],
  ['KL-83', 'Konni', 'Pathanamthitta District'],
  ['KL-84', 'Kondotty', 'Malappuram District'],
  ['KL-85', 'Ramanattukara-Feroke', 'Kozhikode District'],
  ['KL-86', 'Payyannur', 'Kannur District'],
  ['KL-90', 'Nationalised Sector II', 'Thiruvananthapuram', 'Government vehicles: KL-90A state, KL-90B central, KL-90C local body, KL-90D PSU'],
  ['KL-99', 'Thiruvananthapuram', 'Thiruvananthapuram', 'State Transport Authority vehicles, limited circulation'],
];

const LA = [
  ['LA-01', 'Kargil', 'Kargil District', 'Previously JK-07'],
  ['LA-02', 'Leh', 'Leh District', 'Previously JK-10'],
];

const LD = [
  ['LD-01', 'Kavaratti', 'Kavaratti'],
  ['LD-02', 'Agatti', 'Agatti'],
  ['LD-03', 'Amini', 'Amini'],
  ['LD-04', 'Androth', 'Androth'],
  ['LD-05', 'Kadmat', 'Kadmat'],
  ['LD-06', 'Kiltan', 'Kiltan'],
  ['LD-07', 'Kalpeni', 'Kalpeni'],
  ['LD-08', 'Kalpeni', 'Kalpeni'],
  ['LD-09', 'Minicoy', 'Minicoy'],
];

const MH = [
  ['MH-01', 'Mumbai Central, Tardeo', 'Mumbai City District', 'BEST buses, MCGM, Government vehicles also registered here'],
  ['MH-02', 'Mumbai West, Andheri (W)', 'Mumbai Suburban District'],
  ['MH-03', 'Mumbai East, Wadala Truck Terminal', 'Mumbai City District'],
  ['MH-04', 'Thane', 'Thane'],
  ['MH-05', 'Kalyan', 'Thane District'],
  ['MH-06', 'Raigad, Pen', 'Raigad'],
  ['MH-07', 'Sindhudurg', 'Sindhudurg District'],
  ['MH-08', 'Ratnagiri', 'Ratnagiri District'],
  ['MH-09', 'Kolhapur', 'Kolhapur'],
  ['MH-10', 'Sangli', 'Sangli District'],
  ['MH-11', 'Satara', 'Satara'],
  ['MH-12', 'Pune', 'Pune'],
  ['MH-13', 'Solapur', 'Solapur'],
  ['MH-14', 'Pimpri-Chinchwad', 'Pune District'],
  ['MH-15', 'Nashik', 'Nashik'],
  ['MH-16', 'Ahilyanagar', 'Ahilyanagar'],
  ['MH-17', 'Shrirampur', 'Ahilyanagar District'],
  ['MH-18', 'Dhule', 'Dhule District'],
  ['MH-19', 'Jalgaon', 'Jalgaon'],
  ['MH-20', 'Chhatrapati Sambhaji Nagar', 'Chhatrapati Sambhaji Nagar District'],
  ['MH-21', 'Jalna', 'Jalna District'],
  ['MH-22', 'Parbhani', 'Parbhani District'],
  ['MH-23', 'Beed', 'Beed'],
  ['MH-24', 'Latur', 'Latur'],
  ['MH-25', 'Dharashiv', 'Dharashiv District'],
  ['MH-26', 'Nanded', 'Nanded District'],
  ['MH-27', 'Amravati', 'Amaravati District'],
  ['MH-28', 'Buldhana', 'Buldhana'],
  ['MH-29', 'Yavatmal', 'Yavatmal District'],
  ['MH-30', 'Akola', 'Akola District'],
  ['MH-31', 'Nagpur West', 'Nagpur'],
  ['MH-32', 'Wardha', 'Wardha District'],
  ['MH-33', 'Gadchiroli', 'Gadchiroli District'],
  ['MH-34', 'Chandrapur', 'Chandrapur District'],
  ['MH-35', 'Gondia', 'Gondia District'],
  ['MH-36', 'Bhandara', 'Bhandara District'],
  ['MH-37', 'Washim', 'Washim District'],
  ['MH-38', 'Hingoli', 'Hingoli District'],
  ['MH-39', 'Nandurbar', 'Nandurbar District'],
  ['MH-40', 'Nagpur Rural', 'Nagpur District'],
  ['MH-41', 'Malegaon', 'Nashik District'],
  ['MH-42', 'Baramati', 'Pune District'],
  ['MH-43', 'Navi Mumbai', 'Thane District'],
  ['MH-44', 'Ambajogai', 'Beed District'],
  ['MH-45', 'Akluj', 'Solapur District'],
  ['MH-46', 'Panvel', 'Raigad District'],
  ['MH-47', 'Mumbai North (Borivali)', 'Mumbai Suburban District'],
  ['MH-48', 'Vasai', 'Palghar'],
  ['MH-49', 'Nagpur East', 'Nagpur'],
  ['MH-50', 'Karad', 'Satara District'],
  ['MH-51', 'Ichalkaranji', 'Kolhapur District'],
  ['MH-52', 'Chalisgaon', 'Jalgaon District'],
  ['MH-53', 'Phaltan', 'Satara District'],
  ['MH-54', 'Bhadgaon', 'Jalgaon District'],
  ['MH-55', 'Udgir', 'Latur District'],
  ['MH-56', 'Khamgaon', 'Buldhana District'],
  ['MH-57', 'Vaijapur', 'Chhatrapati Sambhaji Nagar District'],
  ['MH-58', 'Mira-Bhayander', 'Thane District'],
  ['MH-59', 'Jath', 'Sangli District', 'Yet to appear on Vahan Website'],
  ['MH-60', 'Palghar', 'Palghar District', 'Announced, yet to appear on Vahan Website'],
];

const ML = [
  ['ML-01', 'Statewide', 'Meghalaya', 'Meghalaya Government vehicles'],
  ['ML-02', 'Statewide', 'Meghalaya', 'Meghalaya Police vehicles'],
  ['ML-04', 'Jowai', 'Jaintia Hills'],
  ['ML-05', 'Shillong', 'Shillong'],
  ['ML-06', 'Nongstoin', 'West Khasi Hills'],
  ['ML-07', 'William Nagar', 'East Garo Hills'],
  ['ML-08', 'Tura', 'West Garo Hills'],
  ['ML-09', 'Baghmara', 'South Garo Hills'],
  ['ML-10', 'Nongpoh', 'Ri-Bhoi'],
];

const MN = [
  ['MN-01', 'Imphal West', 'Imphal West'],
  ['MN-02', 'Churachandpur', 'Churachandpur'],
  ['MN-03', 'Kangpokpi', 'Kangpokpi'],
  ['MN-04', 'Thoubal', 'Thoubal'],
  ['MN-05', 'Bishnupur', 'Bishnupur'],
  ['MN-06', 'Imphal East', 'Imphal East'],
  ['MN-07', 'Ukhrul', 'Ukhrul'],
  ['MN-08', 'Senapati', 'Senapati'],
];

const MP = [
  ['MP-01', 'Bhopal', 'entire Madhya Pradesh', 'Governor of Madhya Pradesh vehicles'],
  ['MP-02', 'Bhopal', 'entire Madhya Pradesh', 'MP Government vehicles'],
  ['MP-03', 'Bhopal', 'entire Madhya Pradesh', 'MP Police vehicles'],
  ['MP-04', 'Bhopal', 'Bhopal'],
  ['MP-05', 'Hoshangabad', 'Hoshangabad'],
  ['MP-06', 'Morena', 'Morena'],
  ['MP-07', 'Gwalior', 'Gwalior'],
  ['MP-08', 'Guna', 'Guna'],
  ['MP-09', 'Indore', 'Indore'],
  ['MP-10', 'Khargone', 'Khargone'],
  ['MP-11', 'Dhar', 'Dhar'],
  ['MP-12', 'Khandwa', 'Khandwa'],
  ['MP-13', 'Ujjain', 'Ujjain'],
  ['MP-14', 'Mandsaur', 'Mandsaur'],
  ['MP-15', 'Sagar', 'Sagar'],
  ['MP-16', 'Chhatarpur', 'Chhatarpur'],
  ['MP-17', 'Rewa', 'Rewa'],
  ['MP-18', 'Shahdol', 'Shahdol'],
  ['MP-19', 'Satna', 'Satna'],
  ['MP-20', 'Jabalpur', 'Jabalpur'],
  ['MP-21', 'Katni', 'Katni'],
  ['MP-22', 'Seoni', 'Seoni'],
  ['MP-28', 'Chhindwara', 'Chhindwara'],
  ['MP-30', 'Bhind', 'Bhind'],
  ['MP-31', 'Sheopur', 'Sheopur'],
  ['MP-32', 'Datia', 'Datia'],
  ['MP-33', 'Shivpuri', 'Shivpuri'],
  ['MP-34', 'Damoh', 'Damoh'],
  ['MP-35', 'Panna', 'Panna'],
  ['MP-36', 'Tikamgarh', 'Tikamgarh'],
  ['MP-37', 'Sehore', 'Sehore'],
  ['MP-38', 'Raisen', 'Raisen'],
  ['MP-39', 'Rajgarh', 'Rajgarh'],
  ['MP-40', 'Vidisha', 'Vidisha'],
  ['MP-41', 'Dewas', 'Dewas'],
  ['MP-42', 'Shajapur', 'Shajapur'],
  ['MP-43', 'Ratlam', 'Ratlam'],
  ['MP-44', 'Neemuch', 'Neemuch'],
  ['MP-45', 'Jhabua', 'Jhabua'],
  ['MP-46', 'Barwani', 'Barwani'],
  ['MP-47', 'Harda', 'Harda'],
  ['MP-48', 'Betul', 'Betul'],
  ['MP-49', 'Narsinghpur', 'Narsinghpur'],
  ['MP-50', 'Balaghat', 'Balaghat'],
  ['MP-51', 'Mandla', 'Mandla'],
  ['MP-52', 'Dindori', 'Dindori'],
  ['MP-53', 'Sidhi', 'Sidhi'],
  ['MP-54', 'Umaria', 'Umaria'],
  ['MP-65', 'Anuppur', 'Anuppur'],
  ['MP-66', 'Waidhan', 'Singrauli'],
  ['MP-67', 'Ashoknagar', 'Ashoknagar'],
  ['MP-68', 'Burhanpur', 'Burhanpur'],
  ['MP-69', 'Alirajpur', 'Alirajpur'],
  ['MP-70', 'Agar', 'Agar Malwa'],
  ['MP-71', 'Niwari', 'Niwari'],
  ['MP-72', 'Mauganj', 'Mauganj'],
  ['MP-73', 'Maihar', 'Maihar'],
  ['MP-74', 'Pandhurna', 'Pandhurna'],
];

const MZ = [
  ['MZ-01', 'Aizawl', 'Aizawl'],
  ['MZ-02', 'Lunglei', 'Lunglei'],
  ['MZ-03', 'Saiha', 'Saiha'],
  ['MZ-04', 'Champhai', 'Champhai'],
  ['MZ-05', 'Kolasib', 'Kolasib'],
  ['MZ-06', 'Serchhip', 'Serchhip'],
  ['MZ-07', 'Lawngtlai', 'Lawngtlai'],
  ['MZ-08', 'Mamit', 'Mamit'],
];

const NL = [
  ['NL-01', 'Kohima', 'Kohima District'],
  ['NL-02', 'Mokokchung District', 'Mokokchung District'],
  ['NL-03', 'Tuensang District', 'Tuensang District'],
  ['NL-04', 'Mon District', 'Mon District'],
  ['NL-05', 'Wokha District', 'Wokha District'],
  ['NL-06', 'Zünheboto District', 'Zünheboto District'],
  ['NL-07', 'Chümoukedima/Dimapur/Niuland', 'Chümoukedima District, Dimapur District, Niuland District'],
  ['NL-08', 'Phek District', 'Phek District'],
  ['NL-09', 'entire Nagaland', 'entire Nagaland', 'Government of Nagaland vehicles (Non-Transport)'],
  ['NL-10', 'entire Nagaland', 'entire Nagaland', 'Government of Nagaland vehicles (Transport)'],
];

const OD = [
  ['OD-01', 'Balasore', 'Balasore district'],
  ['OD-02', 'Bhubaneswar', 'Khurda district'],
  ['OD-03', 'Bolangir', 'Bolangir district'],
  ['OD-04', 'Chandikhol', 'Jajpur district'],
  ['OD-05', 'Cuttack', 'Cuttack district'],
  ['OD-06', 'Dhenkanal', 'Dhenkanal district'],
  ['OD-07', 'Chatrapur', 'Ganjam district'],
  ['OD-08', 'Bhawanipatna', 'Kalahandi district'],
  ['OD-09', 'Keonjhar', 'Keonjhar district'],
  ['OD-10', 'Koraput', 'Koraput district'],
  ['OD-11', 'Baripada', 'Mayurbhanj district'],
  ['OD-12', 'Phulbani', 'Kandhamal district'],
  ['OD-13', 'Puri', 'Puri district'],
  ['OD-14', 'Rourkela', 'Sundargarh district'],
  ['OD-15', 'Sambalpur', 'Sambalpur district'],
  ['OD-16', 'Sundargarh', 'Sundargarh district'],
  ['OD-17', 'Bargarh', 'Bargarh district'],
  ['OD-18', 'Rayagada', 'Rayagada district'],
  ['OD-19', 'Angul', 'Angul district'],
  ['OD-20', 'Paralakhemundi', 'Gajapati district'],
  ['OD-21', 'Jagatsinghpur', 'Jagatsinghpur district'],
  ['OD-22', 'Bhadrak', 'Bhadrak district'],
  ['OD-23', 'Jharsuguda', 'Jharsuguda district'],
  ['OD-24', 'Nabarangpur', 'Nabarangpur district'],
  ['OD-25', 'Nayagarh', 'Nayagarh district'],
  ['OD-26', 'Nuapada', 'Nuapada district'],
  ['OD-27', 'Boudh', 'Boudh district'],
  ['OD-28', 'Debagarh', 'Debagarh district'],
  ['OD-29', 'Kendrapara', 'Kendrapara district'],
  ['OD-30', 'Malkangiri', 'Malkangiri district'],
  ['OD-31', 'Subarnapur', 'Subarnapur district'],
  ['OD-32', 'Bhanjanagar', 'Ganjam district'],
  ['OD-33', 'Bhubaneswar-II', 'Khurda district'],
  ['OD-34', 'Jajpur', 'Jajpur district'],
  ['OD-35', 'Talcher', 'Angul district'],
];

const PB = [
  ['PB-01', 'Chandigarh', 'Punjab', 'Rented cars, self-drive cars in Chandigarh & taxi vehicles from Punjab'],
  ['PB-02', 'Amritsar (1)', 'Amritsar'],
  ['PB-03', 'Bathinda', 'Bathinda'],
  ['PB-04', 'Faridkot', 'Faridkot'],
  ['PB-05', 'Ferozpur', 'Ferozpur'],
  ['PB-06', 'Gurdaspur', 'Gurdaspur'],
  ['PB-07', 'Hoshiarpur', 'Hoshiarpur'],
  ['PB-08', 'Jalandhar (1)', 'Jalandhar'],
  ['PB-09', 'Kapurthala', 'Kapurthala'],
  ['PB-10', 'Ludhiana (West)', 'Ludhiana'],
  ['PB-11', 'Patiala', 'Patiala'],
  ['PB-12', 'Rupnagar', 'Rupnagar'],
  ['PB-13', 'Sangrur', 'Sangrur'],
  ['PB-14', 'Ajnala', 'Amritsar'],
  ['PB-15', 'Abohar', 'Fazilka'],
  ['PB-16', 'Anandpur Sahib', 'Rupnagar'],
  ['PB-17', 'Baba Bakala', 'Amritsar'],
  ['PB-18', 'Batala', 'Gurdaspur'],
  ['PB-19', 'Barnala', 'Barnala'],
  ['PB-20', 'Balachaur', 'Shaheed Bhagat Singh Nagar'],
  ['PB-21', 'Dasuya', 'Hoshiarpur'],
  ['PB-22', 'Fazilka', 'Fazilka'],
  ['PB-23', 'Fatehgarh Sahib', 'Fatehgarh Sahib'],
  ['PB-24', 'Garhshankar', 'Hoshiarpur'],
  ['PB-25', 'Jagraon', 'Ludhiana'],
  ['PB-26', 'Khanna', 'Ludhiana'],
  ['PB-27', 'Kharar', 'Mohali'],
  ['PB-28', 'Malerkotla', 'Malerkotla'],
  ['PB-29', 'Moga', 'Moga'],
  ['PB-30', 'Muktsar', 'Muktsar'],
  ['PB-31', 'Mansa', 'Mansa'],
  ['PB-32', 'Nawanshahar', 'Shaheed Bhagat Singh Nagar'],
  ['PB-33', 'Nakodar', 'Jalandhar'],
  ['PB-34', 'Nabha', 'Patiala'],
  ['PB-35', 'Pathankot', 'Pathankot'],
  ['PB-36', 'Phagwara', 'Kapurthala'],
  ['PB-37', 'Phillaur', 'Jalandhar'],
  ['PB-38', 'Patti', 'Tarn Taran'],
  ['PB-39', 'Rajpura', 'Patiala'],
  ['PB-40', 'Rampura Phul', 'Bathinda'],
  ['PB-41', 'Sultanpur Lodhi', 'Kapurthala'],
  ['PB-42', 'Samana', 'Patiala'],
  ['PB-43', 'Samrala', 'Ludhiana'],
  ['PB-44', 'Sunam', 'Sangrur'],
  ['PB-45', 'Talwandi Sabo', 'Bathinda'],
  ['PB-46', 'Tarn Taran', 'Tarn Taran'],
  ['PB-47', 'Zira', 'Ferozpur'],
  ['PB-48', 'Amloh', 'Fatehgarh Sahib'],
  ['PB-49', 'Khamanon', 'Fatehgarh Sahib'],
  ['PB-50', 'Budhlada', 'Mansa'],
  ['PB-51', 'Sardulgarh', 'Mansa'],
  ['PB-52', 'Bassi Pathana', 'Fatehgarh Sahib'],
  ['PB-53', 'Malout', 'Muktsar'],
  ['PB-54', 'Mukerian', 'Hoshiarpur'],
  ['PB-55', 'Payal', 'Ludhiana'],
  ['PB-56', 'Raikot', 'Ludhiana'],
  ['PB-57', 'Bhulath', 'Kapurthala'],
  ['PB-58', 'Dera Baba Nanak', 'Gurdaspur'],
  ['PB-59', 'Dhuri', 'Sangrur'],
  ['PB-60', 'Gidderbaha', 'Muktsar'],
  ['PB-61', 'Jalalabad', 'Fazilka'],
  ['PB-62', 'Jaitu', 'Faridkot'],
  ['PB-63', 'Khadoor Sahib', 'Tarn Taran'],
  ['PB-64', 'Moonak', 'Sangrur'],
  ['PB-65', 'Mohali', 'Mohali'],
  ['PB-66', 'Nihal Singh Wala', 'Moga'],
  ['PB-67', 'Shahkot', 'Jalandhar'],
  ['PB-68', 'Dhar Kalan', 'Pathankot'],
  ['PB-69', 'Bagha Purana', 'Moga'],
  ['PB-70', 'Dera Bassi', 'Mohali'],
  ['PB-71', 'Chamkaur Sahib', 'Rupnagar'],
  ['PB-72', 'Pattran', 'Patiala'],
  ['PB-73', 'Tappa Mandi', 'Barnala'],
  ['PB-74', 'Nangal', 'Rupnagar'],
  ['PB-75', 'Lehragaga', 'Sangrur'],
  ['PB-76', 'Dharamkot', 'Moga'],
  ['PB-77', 'Guru Har Sahai', 'Ferozpur'],
  ['PB-78', 'Banga', 'Shaheed Bhagat Singh Nagar'],
  ['PB-79', 'Kotkapura', 'Faridkot'],
  ['PB-80', 'Maur', 'Bathinda'],
  ['PB-81', 'Majitha', 'Amritsar'],
  ['PB-82', 'Ahmedgarh', 'Malerkotla'],
  ['PB-83', 'Dudhan Sadhan', 'Patiala'],
  ['PB-84', 'Bhawanigarh', 'Sangrur'],
  ['PB-85', 'Kalanaur', 'Gurdaspur'],
  ['PB-86', 'Dirba', 'Sangrur'],
  ['PB-87', 'Morinda', 'Rupnagar'],
  ['PB-88', 'Bhikhiwind', 'Tarn Taran'],
  ['PB-89', 'Amritsar (2)', 'Amritsar'],
  ['PB-90', 'Jalandhar (2)', 'Jalandhar'],
  ['PB-91', 'Ludhiana (East)', 'Ludhiana'],
  ['PB-92', 'Amargarh', 'Malerkotla'],
  ['PB-93', 'Lopoke', 'Amritsar'],
  ['PB-99', 'Dinanagar', 'Gurdaspur'],
];

const PY = [
  ['PY-01', 'Puducherry', 'Puducherry'],
  ['PY-02', 'Karaikal', 'Karaikal'],
  ['PY-03', 'Mahe', 'Mahe'],
  ['PY-04', 'Yanam', 'Yanam'],
  ['PY-05', 'Oulgaret', 'Oulgaret'],
];

const RJ = [
  ['RJ-01', 'Ajmer', 'Ajmer district'],
  ['RJ-02', 'Alwar', 'Alwar district'],
  ['RJ-03', 'Banswara', 'Banswara district'],
  ['RJ-04', 'Barmer', 'Barmer district'],
  ['RJ-05', 'Bharatpur', 'Bharatpur district'],
  ['RJ-06', 'Bhilwara', 'Bhilwara district'],
  ['RJ-07', 'Bikaner', 'Bikaner district'],
  ['RJ-08', 'Bundi', 'Bundi district'],
  ['RJ-09', 'Chittorgarh', 'Chittorgarh district'],
  ['RJ-10', 'Churu', 'Churu district'],
  ['RJ-11', 'Dholpur', 'Dholpur district'],
  ['RJ-12', 'Dungarpur', 'Dungarpur district'],
  ['RJ-13', 'Sri Ganganagar', 'Sri Ganganagar district'],
  ['RJ-14', 'Jaipur (South)', 'Jaipur district'],
  ['RJ-15', 'Jaisalmer', 'Jaisalmer district'],
  ['RJ-16', 'Jalore', 'Jalore district'],
  ['RJ-17', 'Jhalawar', 'Jhalawar district'],
  ['RJ-18', 'Jhunjhunu', 'Jhunjhunu district'],
  ['RJ-19', 'Jodhpur', 'Jodhpur district'],
  ['RJ-20', 'Kota', 'Kota district'],
  ['RJ-21', 'Nagaur', 'Nagaur district'],
  ['RJ-22', 'Pali', 'Pali district'],
  ['RJ-23', 'Sikar', 'Sikar district'],
  ['RJ-24', 'Sirohi', 'Sirohi district'],
  ['RJ-25', 'Sawai Madhopur', 'Sawai Madhopur district'],
  ['RJ-26', 'Tonk', 'Tonk district'],
  ['RJ-27', 'Udaipur', 'Udaipur district'],
  ['RJ-28', 'Baran', 'Baran district'],
  ['RJ-29', 'Dausa', 'Dausa district'],
  ['RJ-30', 'Rajsamand', 'Rajsamand district'],
  ['RJ-31', 'Hanumangarh', 'Hanumangarh district'],
  ['RJ-32', 'Kotputli', 'Kotputli-Behror district'],
  ['RJ-33', 'Ramganj Mandi', 'Kota district'],
  ['RJ-34', 'Karauli', 'Karauli district'],
  ['RJ-35', 'Pratapgarh', 'Pratapgarh district'],
  ['RJ-36', 'Beawar', 'Beawar District'],
  ['RJ-37', 'Didwana', 'Didwana-Kuchaman district'],
  ['RJ-38', 'Abu Road', 'Sirohi district'],
  ['RJ-39', 'Balotra', 'Balotra district'],
  ['RJ-40', 'Bhiwadi', 'Khairthal-Tijara district'],
  ['RJ-41', 'Chomu', 'Jaipur district'],
  ['RJ-42', 'Kishangarh', 'Ajmer district'],
  ['RJ-43', 'Phalodi', 'Phalodi district'],
  ['RJ-44', 'Sujangarh', 'Churu district'],
  ['RJ-45', 'Jaipur (North)', 'Jaipur district'],
  ['RJ-46', 'Bhinmal', 'Jalore district'],
  ['RJ-47', 'Dudu', 'Jaipur district'],
  ['RJ-48', 'Kekri', 'Ajmer district'],
  ['RJ-49', 'Nohar', 'Hanumangarh district'],
  ['RJ-50', 'Nokha', 'Bikaner district'],
  ['RJ-51', 'Shahpura', 'Bhilwara district'],
  ['RJ-52', 'Shahpura', 'Jaipur district'],
  ['RJ-53', 'Khetri', 'Jhunjhunu district'],
  ['RJ-54', 'Piparcity', 'Jodhpur district'],
  ['RJ-55', 'Pokhran', 'Jaisalmer district'],
  ['RJ-56', 'Sadulshahar', 'Sri Ganganagar district'],
  ['RJ-57', 'Sumerpur', 'Pali district'],
  ['RJ-58', 'Salumbar', 'Salumbar district'],
  ['RJ-59', 'Shahpura', 'Jaipur district'],
  ['RJ-60', 'Jaipur (Additional)', 'Jaipur district'],
];

const SK = [
  ['SK-01', 'Gangtok', 'Gangtok'],
  ['SK-02', 'Gyalshing', 'Gyalshing district'],
  ['SK-03', 'Mangan', 'Mangan'],
  ['SK-04', 'Jorethang', 'Namchi district'],
  ['SK-05', 'Namchi', 'Namchi district'],
  ['SK-06', 'Soreng', 'Soreng district'],
  ['SK-07', 'Pakyong', 'Pakyong district'],
  ['SK-08', 'Singtam', 'Singtam'],
];

const TG = [
  ['TG-01', 'Adilabad', 'Adilabad district'],
  ['TG-02', 'Karimnagar', 'Karimnagar district'],
  ['TG-03', 'Warangal', 'Hanamkonda district'],
  ['TG-04', 'Khammam', 'Khammam district'],
  ['TG-05', 'Nalgonda', 'Nalgonda district'],
  ['TG-06', 'Mahbubnagar', 'Mahbubnagar district'],
  ['TG-07', 'Attapur (Hyderabad)', 'Ranga Reddy'],
  ['TG-08', 'Medchal (Hyderabad)', 'Medchal-Malkajgiri District'],
  ['TG-09', 'Khairtabad (Hyderabad)', 'Hyderabad Central'],
  ['TG-10', 'Secunderabad (Hyderabad)', 'Hyderabad North'],
  ['TG-11', 'Malakpet (Hyderabad)', 'Hyderabad East'],
  ['TG-12', 'Kishanbagh (Hyderabad)', 'Hyderabad South'],
  ['TG-13', 'Tolichowki (Hyderabad)', 'Hyderabad West'],
  ['TG-14', 'Hyderabad', 'Hyderabad', 'Reserved for Hyderabad'],
  ['TG-15', 'Sangareddy', 'Sangareddy district'],
  ['TG-16', 'Nizamabad', 'Nizamabad district'],
  ['TG-17', 'Kamareddy', 'Kamareddy district'],
  ['TG-18', 'Nirmal', 'Nirmal district'],
  ['TG-19', 'Mancherial', 'Mancherial district'],
  ['TG-20', 'Asifabad', 'Komaram Bheem district'],
  ['TG-21', 'Jagtial', 'Jagtial district'],
  ['TG-22', 'Peddapalli', 'Peddapalli district'],
  ['TG-23', 'Sircilla', 'Sircilla district'],
  ['TG-24', 'Warangal', 'Warangal district'],
  ['TG-25', 'Bhupalpalle', 'Jayashankar Bhupalpally district'],
  ['TG-26', 'Mahabubabad', 'Mahabubabad district'],
  ['TG-27', 'Jangaon', 'Jangaon district'],
  ['TG-28', 'Kothagudem', 'Bhadradri Kothagudem district'],
  ['TG-29', 'Suryapet', 'Suryapet district'],
  ['TG-30', 'Bhuvanagiri', 'Yadadri Bhuvanagiri district', 'Hyderabad Border District'],
  ['TG-31', 'Nagarkurnool', 'Nagarkurnool district'],
  ['TG-32', 'Wanaparthy', 'Wanaparthy district'],
  ['TG-33', 'Gadwal', 'Jogulamba Gadwal district'],
  ['TG-34', 'Vikarabad', 'Vikarabad district'],
  ['TG-35', 'Medak', 'Medak district'],
  ['TG-36', 'Siddipet', 'Siddipet district'],
  ['TG-37', 'Mulugu', 'Mulugu district'],
  ['TG-38', 'Narayanpet', 'Narayanpet district'],
];

const TN = [
  ['TN-01', 'Chennai (Central): Ayanavaram', 'Chennai', 'SETC & MTC buses registered under TN 01 N XXXX'],
  ['TN-02', 'Chennai (North West): Anna Nagar', 'Chennai'],
  ['TN-03', 'Chennai (North East): Tondiarpet', 'Chennai'],
  ['TN-04', 'Chennai (East): Royapuram', 'Chennai'],
  ['TN-05', 'Chennai (North): Kolathur', 'Chennai'],
  ['TN-06', 'Chennai (South East): Mandavelli', 'Chennai'],
  ['TN-07', 'Chennai (South): Adyar', 'Chennai'],
  ['TN-09', 'Chennai (West): K. K. Nagar', 'Chennai'],
  ['TN-10', 'Chennai (South West): Virugambakkam', 'Chennai'],
  ['TN-11', 'Tambaram', 'Chengalpattu'],
  ['TN-12', 'Poonamallee', 'Tiruvallur'],
  ['TN-13', 'Ambattur', 'Chennai'],
  ['TN-14', 'Sholinganallur', 'Chengalpattu'],
  ['TN-15', 'Ulundurpet', 'Kallakurichi'],
  ['TN-16', 'Tindivanam', 'Villupuram'],
  ['TN-18', 'Red Hills', 'Tiruvallur'],
  ['TN-19', 'Chengalpattu', 'Chengalpattu'],
  ['TN-20', 'Tiruvallur', 'Tiruvallur'],
  ['TN-21', 'Kanchipuram', 'Kanchipuram'],
  ['TN-22', 'Meenambakkam', 'Chennai'],
  ['TN-23', 'Vellore', 'Vellore'],
  ['TN-24', 'Krishnagiri', 'Krishnagiri'],
  ['TN-25', 'Thiruvannamalai', 'Thiruvannamalai'],
  ['TN-27', 'Salem', 'Salem', 'Not in use'],
  ['TN-28', 'Namakkal (North)', 'Namakkal'],
  ['TN-29', 'Dharmapuri', 'Dharmapuri'],
  ['TN-30', 'Salem (West)', 'Salem'],
  ['TN-31', 'Cuddalore', 'Cuddalore'],
  ['TN-32', 'Villupuram', 'Villupuram'],
  ['TN-33', 'Erode (East)', 'Erode'],
  ['TN-34', 'Tiruchengode', 'Namakkal'],
  ['TN-36', 'Gobichettipalayam', 'Erode'],
  ['TN-37', 'Coimbatore (South)', 'Coimbatore'],
  ['TN-38', 'Coimbatore (North)', 'Coimbatore'],
  ['TN-39', 'Tirupur (North)', 'Tirupur'],
  ['TN-40', 'Mettupalayam', 'Coimbatore'],
  ['TN-41', 'Pollachi', 'Coimbatore'],
  ['TN-42', 'Tirupur (South)', 'Tirupur'],
  ['TN-43', 'Ooty', 'Nilgiris'],
  ['TN-45', 'Tiruchirapalli (West)', 'Tiruchirapalli'],
  ['TN-46', 'Perambalur', 'Perambalur'],
  ['TN-47', 'Karur', 'Karur'],
  ['TN-48', 'Srirangam', 'Tiruchirapalli'],
  ['TN-49', 'Thanjavur', 'Thanjavur'],
  ['TN-50', 'Tiruvarur', 'Tiruvarur'],
  ['TN-51', 'Nagapattinam', 'Nagapattinam'],
  ['TN-52', 'Sankagiri', 'Salem'],
  ['TN-54', 'Salem (East)', 'Salem'],
  ['TN-55', 'Pudukottai', 'Pudukottai'],
  ['TN-56', 'Perundurai', 'Erode'],
  ['TN-57', 'Dindigul', 'Dindigul'],
  ['TN-58', 'Madurai (South)', 'Madurai'],
  ['TN-59', 'Madurai (North)', 'Madurai'],
  ['TN-60', 'Theni', 'Theni'],
  ['TN-61', 'Ariyalur', 'Ariyalur'],
  ['TN-63', 'Sivaganga', 'Sivaganga'],
  ['TN-64', 'Madurai (Central)', 'Madurai'],
  ['TN-65', 'Ramanathapuram', 'Ramanathapuram'],
  ['TN-66', 'Coimbatore (Central)', 'Coimbatore'],
  ['TN-67', 'Virudhunagar', 'Virudhunagar'],
  ['TN-68', 'Kumbakonam', 'Thanjavur'],
  ['TN-69', 'Thoothukudi', 'Thoothukudi'],
  ['TN-70', 'Hosur', 'Krishnagiri'],
  ['TN-72', 'Tirunelveli', 'Tirunelveli'],
  ['TN-73', 'Ranipet', 'Ranipet'],
  ['TN-74', 'Nagercoil', 'Kanniyakumari'],
  ['TN-75', 'Marthandam', 'Kanniyakumari'],
  ['TN-76', 'Tenkasi', 'Tenkasi'],
  ['TN-77', 'Attur', 'Salem'],
  ['TN-78', 'Dharapuram', 'Tirupur'],
  ['TN-79', 'Sankarankovil', 'Tenkasi'],
  ['TN-81', 'Tiruchirapalli (East)', 'Tiruchirapalli'],
  ['TN-82', 'Mayiladuthurai', 'Mayiladuthurai'],
  ['TN-83', 'Vaniyambadi', 'Thirupattur'],
  ['TN-84', 'Srivilliputhur', 'Virudhunagar'],
  ['TN-85', 'Kundrathur', 'Kanchipuram'],
  ['TN-86', 'Erode (West)', 'Erode'],
  ['TN-87', 'Sriperumbudur', 'Kanchipuram'],
  ['TN-88', 'Namakkal (South)', 'Namakkal'],
  ['TN-90', 'Salem (South)', 'Salem'],
  ['TN-91', 'Chidambaram', 'Cuddalore'],
  ['TN-92', 'Thiruchendur', 'Thoothukudi'],
  ['TN-93', 'Mettur', 'Salem'],
  ['TN-94', 'Palani', 'Dindigul'],
  ['TN-95', 'Sivakasi', 'Virudhunagar'],
  ['TN-96', 'Kovilpatti', 'Thoothukudi'],
  ['TN-97', 'Arani', 'Tiruvannamalai'],
  ['TN-99', 'Coimbatore (West)', 'Coimbatore'],
];

const TR = [
  ['TR-01', 'Agartala', 'West Tripura'],
  ['TR-02', 'Kailasahar', 'Unakoti'],
  ['TR-03', 'Udaipur', 'Gomati'],
  ['TR-04', 'Ambassa', 'Dhalai'],
  ['TR-05', 'Dharmanagar', 'North Tripura'],
  ['TR-06', 'Teliamura', 'Khowai'],
  ['TR-07', 'Bishramganj', 'Sipahijala'],
  ['TR-08', 'Santirbazar', 'South Tripura'],
];

const UK = [
  ['UK-01', 'Almora', 'Almora district'],
  ['UK-02', 'Bageshwar', 'Bageshwar district'],
  ['UK-03', 'Champawat', 'Champawat district'],
  ['UK-04', 'Haldwani', 'Nainital district'],
  ['UK-05', 'Pithoragarh', 'Pithoragarh district'],
  ['UK-06', 'Rudrapur', 'Udham Singh Nagar district'],
  ['UK-07', 'Dehradun', 'Dehradun district'],
  ['UK-08', 'Haridwar', 'Haridwar district'],
  ['UK-09', 'Tehri', 'Tehri Garhwal district'],
  ['UK-10', 'Uttarkashi', 'Uttarkashi district'],
  ['UK-11', 'Gopeshwar', 'Chamoli district'],
  ['UK-12', 'Pauri', 'Pauri Garhwal district'],
  ['UK-13', 'Rudraprayag', 'Rudraprayag district'],
  ['UK-14', 'Rishikesh', 'Dehradun district'],
  ['UK-15', 'Kotdwar', 'Pauri Garhwal district'],
  ['UK-16', 'Vikasnagar', 'Dehradun district'],
  ['UK-17', 'Roorkee', 'Haridwar district'],
  ['UK-18', 'Kashipur', 'Udham Singh Nagar district'],
  ['UK-19', 'Ramnagar', 'Nainital District'],
  ['UK-20', 'Ranikhet', 'Almora District'],
];

const UP = [
  ['UP-11', 'Saharanpur', 'Saharanpur district'],
  ['UP-12', 'Muzaffarnagar', 'Muzaffarnagar district'],
  ['UP-13', 'Bulandshahr', 'Bulandshahr district'],
  ['UP-14', 'Ghaziabad', 'Ghaziabad district'],
  ['UP-15', 'Meerut', 'Meerut district'],
  ['UP-16', 'Noida', 'Gautam Buddha Nagar district'],
  ['UP-17', 'Baghpat', 'Bagpat district'],
  ['UP-19', 'Shamli', 'Shamli district'],
  ['UP-20', 'Bijnor', 'Bijnor district'],
  ['UP-21', 'Moradabad', 'Moradabad district', '21G government, 21N commercial'],
  ['UP-22', 'Rampur', 'Rampur district', '22G government, 22T commercial'],
  ['UP-23', 'Amroha', 'Amroha district'],
  ['UP-24', 'Badaun', 'Badaun district'],
  ['UP-25', 'Bareilly', 'Bareilly district'],
  ['UP-26', 'Pilibhit', 'Pilibhit district'],
  ['UP-27', 'Shahjahanpur', 'Shahjahanpur district'],
  ['UP-30', 'Hardoi', 'Hardoi district'],
  ['UP-31', 'Lakhimpur', 'Lakhimpur Kheri district'],
  ['UP-32', 'Lucknow', 'Lucknow district'],
  ['UP-33', 'Raebareli', 'Raebareli district'],
  ['UP-34', 'Sitapur', 'Sitapur district'],
  ['UP-35', 'Unnao', 'Unnao district'],
  ['UP-36', 'Amethi', 'Amethi district'],
  ['UP-37', 'Hapur', 'Hapur district'],
  ['UP-38', 'Bahjoi', 'Sambhal district'],
  ['UP-40', 'Bahraich', 'Bahraich district'],
  ['UP-41', 'Barabanki', 'Barabanki district'],
  ['UP-42', 'Ayodhya', 'Ayodhya district'],
  ['UP-43', 'Gonda', 'Gonda district'],
  ['UP-44', 'Sultanpur', 'Sultanpur district'],
  ['UP-45', 'Akbarpur', 'Ambedkar Nagar'],
  ['UP-46', 'Shravasti', 'Shravasti district'],
  ['UP-47', 'Balrampur', 'Balrampur district'],
  ['UP-50', 'Azamgarh', 'Azamgarh district'],
  ['UP-51', 'Basti', 'Basti district'],
  ['UP-52', 'Deoria', 'Deoria district'],
  ['UP-53', 'Gorakhpur', 'Gorakhpur district'],
  ['UP-54', 'Mau', 'Mau district'],
  ['UP-55', 'Siddharthnagar', 'Siddharth Nagar'],
  ['UP-56', 'Maharajganj', 'Maharajganj district'],
  ['UP-57', 'Padrauna', 'Kushinagar district'],
  ['UP-58', 'Khalilabad', 'Sant Kabir Nagar'],
  ['UP-60', 'Ballia', 'Ballia district'],
  ['UP-61', 'Ghazipur', 'Ghazipur district'],
  ['UP-62', 'Jaunpur', 'Jaunpur district'],
  ['UP-63', 'Mirzapur', 'Mirzapur district'],
  ['UP-64', 'Robertsganj', 'Sonbhadra district'],
  ['UP-65', 'Varanasi', 'Varanasi district'],
  ['UP-66', 'Gyanpur', 'Bhadohi district'],
  ['UP-67', 'Chandauli', 'Chandauli district'],
  ['UP-70', 'Prayagraj', 'Prayagraj district'],
  ['UP-71', 'Fatehpur', 'Fatehpur district'],
  ['UP-72', 'Pratapgarh', 'Pratapgarh district'],
  ['UP-73', 'Manjhanpur', 'Kaushambi'],
  ['UP-74', 'Kannauj', 'Kannauj district'],
  ['UP-75', 'Etawah', 'Etawah district'],
  ['UP-76', 'Farrukhabad', 'Farrukhabad district'],
  ['UP-77', 'Akbarpur', 'Kanpur Dehat district'],
  ['UP-78', 'Kanpur', 'Kanpur Nagar district'],
  ['UP-79', 'Auraiya', 'Auraiya district'],
  ['UP-80', 'Agra', 'Agra district'],
  ['UP-81', 'Aligarh', 'Aligarh district'],
  ['UP-82', 'Etah', 'Etah district'],
  ['UP-83', 'Firozabad', 'Firozabad district'],
  ['UP-84', 'Mainpuri', 'Mainpuri district'],
  ['UP-85', 'Mathura', 'Mathura district'],
  ['UP-86', 'Hathras', 'Hathras district'],
  ['UP-87', 'Kasganj', 'Kasganj district'],
  ['UP-90', 'Banda', 'Banda district'],
  ['UP-91', 'Hamirpur', 'Hamirpur district'],
  ['UP-92', 'Jalaun', 'Jalaun district'],
  ['UP-93', 'Jhansi', 'Jhansi district'],
  ['UP-94', 'Lalitpur', 'Lalitpur district'],
  ['UP-95', 'Mahoba', 'Mahoba district'],
  ['UP-96', 'Chitrakoot Dham', 'Chitrakoot district'],
];

const WB = [
  ['WB-01', 'Beltala (two wheelers)', 'Kolkata district', 'WB-01BB is new series under One RTO One Code initiative'],
  ['WB-02', 'Beltala (four wheelers)', 'Kolkata district', 'Discontinued, replaced by WB-01BB'],
  ['WB-03', 'Beltala (commercial goods)', 'Kolkata district', 'Discontinued'],
  ['WB-04', 'Beltala (commercial passenger)', 'Kolkata district'],
  ['WB-05', 'Kasba (commercial)', 'Kolkata district', 'WB-05B is the new code under One RTO One Code'],
  ['WB-06', 'Kasba (private)', 'Kolkata district'],
  ['WB-07', 'Salt Lake (commercial)', 'Kolkata district'],
  ['WB-08', 'Salt Lake (private)', 'Kolkata district'],
  ['WB-09', 'Behala (commercial)', 'Kolkata district', 'Replaced by WB-09B'],
  ['WB-10', 'Behala (private)', 'Kolkata district', 'Replaced by WB-09B'],
  ['WB-11', 'Howrah (commercial)', 'Howrah district', 'Replaced by WB-11H'],
  ['WB-12', 'Howrah (private)', 'Howrah district', 'Replaced by WB-11H'],
  ['WB-13', 'Uluberia (commercial)', 'Howrah district', 'Replaced by WB-13B'],
  ['WB-14', 'Uluberia (private)', 'Howrah district'],
  ['WB-15', 'Chinsurah (commercial)', 'Hooghly district', 'Replaced by WB-15E'],
  ['WB-16', 'Chinsurah (private)', 'Hooghly district', 'Replaced by WB-15E'],
  ['WB-17', 'Serampore (commercial)', 'Hooghly district'],
  ['WB-18', 'Serampore (private)', 'Hooghly district'],
  ['WB-19', 'Alipore (commercial)', 'South 24 Parganas district'],
  ['WB-20', 'Alipore (private)', 'South 24 Parganas district', 'Discontinued, replaced by WB-19P'],
  ['WB-21', 'Basirhat (commercial)', 'North 24 Parganas district'],
  ['WB-22', 'Basirhat (private)', 'North 24 Parganas district'],
  ['WB-23', 'Barrackpore (commercial)', 'North 24 Parganas district'],
  ['WB-24', 'Barrackpore (private)', 'North 24 Parganas district', 'Replaced by WB-23H'],
  ['WB-25', 'Barasat (commercial)', 'North 24 Parganas district'],
  ['WB-26', 'Barasat (private)', 'North 24 Parganas district', 'Replaced by WB-25N'],
  ['WB-27', 'Bangaon (commercial)', 'North 24 Parganas district'],
  ['WB-28', 'Bangaon (private)', 'North 24 Parganas district'],
  ['WB-29', 'Tamluk (commercial)', 'Purba Medinipur district'],
  ['WB-30', 'Tamluk (private)', 'Purba Medinipur district'],
  ['WB-31', 'Contai (commercial)', 'Purba Medinipur district'],
  ['WB-32', 'Contai (private)', 'Purba Medinipur district'],
  ['WB-33', 'Medinipur (commercial)', 'Paschim Medinipur district'],
  ['WB-34', 'Medinipur (private)', 'Paschim Medinipur district'],
  ['WB-35', 'Kharagpur (commercial)', 'Paschim Medinipur district'],
  ['WB-36', 'Kharagpur (private)', 'Paschim Medinipur district'],
  ['WB-37', 'Asansol (commercial)', 'Paschim Bardhaman district'],
  ['WB-38', 'Asansol (private)', 'Paschim Bardhaman district'],
  ['WB-39', 'Durgapur (commercial)', 'Paschim Bardhaman district', 'SBSTC buses also registered here'],
  ['WB-40', 'Durgapur (private)', 'Paschim Bardhaman district'],
  ['WB-41', 'Bardhaman (commercial)', 'Purba Bardhaman district'],
  ['WB-42', 'Bardhaman (private)', 'Purba Bardhaman district'],
  ['WB-43', 'Kalna (commercial)', 'Purba Bardhaman district'],
  ['WB-44', 'Kalna (private)', 'Purba Bardhaman district'],
  ['WB-45', 'Rampurhat (commercial)', 'Birbhum district'],
  ['WB-46', 'Rampurhat (private)', 'Birbhum district'],
  ['WB-47', 'Bolpur (commercial)', 'Birbhum district'],
  ['WB-48', 'Bolpur (private)', 'Birbhum district'],
  ['WB-49', 'Jhargram (commercial)', 'Jhargram district'],
  ['WB-50', 'Jhargram (private)', 'Jhargram district'],
  ['WB-51', 'Krishnanagar (commercial)', 'Nadia district'],
  ['WB-52', 'Krishnanagar (private)', 'Nadia district'],
  ['WB-53', 'Birbhum (commercial)', 'Birbhum district'],
  ['WB-54', 'Birbhum (private)', 'Birbhum district'],
  ['WB-55', 'Purulia (commercial)', 'Purulia district'],
  ['WB-56', 'Purulia (private)', 'Purulia district'],
  ['WB-57', 'Murshidabad (commercial)', 'Murshidabad district'],
  ['WB-58', 'Murshidabad (private)', 'Murshidabad district'],
  ['WB-59', 'Raiganj (commercial)', 'Uttar Dinajpur district'],
  ['WB-60', 'Raiganj (private)', 'Uttar Dinajpur district'],
  ['WB-61', 'Balurghat (commercial)', 'Dakshin Dinajpur district'],
  ['WB-62', 'Balurghat (private)', 'Dakshin Dinajpur district'],
  ['WB-63', 'Cooch Behar (commercial)', 'Cooch Behar district', 'NBSTC buses also registered here'],
  ['WB-64', 'Cooch Behar (private)', 'Cooch Behar district'],
  ['WB-65', 'Malda City (commercial)', 'Malda district'],
  ['WB-66', 'Malda City (private)', 'Malda district'],
  ['WB-67', 'Bankura (commercial)', 'Bankura district'],
  ['WB-68', 'Bankura (private)', 'Bankura district'],
  ['WB-69', 'Alipurduar (commercial)', 'Alipurduar district'],
  ['WB-70', 'Alipurduar (private)', 'Alipurduar district'],
  ['WB-71', 'Jalpaiguri (commercial)', 'Jalpaiguri district'],
  ['WB-72', 'Jalpaiguri (private)', 'Jalpaiguri district'],
  ['WB-73', 'Siliguri (commercial)', 'Darjeeling district', 'Replaced by WB-73K'],
  ['WB-74', 'Siliguri (private)', 'Darjeeling district', 'Replaced by WB-73K'],
  ['WB-75', 'Katwa', 'Purba Bardhaman district'],
  ['WB-76', 'Darjeeling (commercial)', 'Darjeeling district'],
  ['WB-77', 'Darjeeling (private)', 'Darjeeling district'],
  ['WB-78', 'Kalimpong (commercial)', 'Kalimpong district'],
  ['WB-79', 'Kalimpong (private)', 'Kalimpong district'],
  ['WB-80', 'Manbazar', 'Purulia district'],
  ['WB-81', 'Raghunathpur (commercial)', 'Purulia district'],
  ['WB-82', 'Raghunathpur (private)', 'Purulia district'],
  ['WB-83', 'Chanchal (commercial)', 'Malda district'],
  ['WB-84', 'Chanchal (private)', 'Malda district'],
  ['WB-85', 'Mathabhanga (commercial)', 'Cooch Behar district'],
  ['WB-86', 'Mathabhanga (private)', 'Cooch Behar district'],
  ['WB-87', 'Bishnupur (commercial)', 'Bankura district'],
  ['WB-88', 'Bishnupur (private)', 'Bankura district'],
  ['WB-89', 'Kalyani (commercial)', 'Nadia district'],
  ['WB-90', 'Kalyani (private)', 'Nadia district'],
  ['WB-91', 'Islampur (commercial)', 'Uttar Dinajpur district'],
  ['WB-92', 'Islampur (private)', 'Uttar Dinajpur district'],
  ['WB-93', 'Jangipur (commercial)', 'Murshidabad district'],
  ['WB-94', 'Jangipur (private)', 'Murshidabad district'],
  ['WB-95', 'Baruipur (commercial)', 'South 24 Parganas district'],
  ['WB-96', 'Baruipur (private)', 'South 24 Parganas district'],
  ['WB-97', 'Diamond Harbour (commercial)', 'South 24 Parganas district'],
  ['WB-98', 'Canning', 'South 24 Parganas district'],
  ['WB-99', 'Kandi', 'Murshidabad district'],
];

module.exports = { KA, KL, LA, LD, MH, ML, MN, MP, MZ, NL, OD, PB, PY, RJ, SK, TG, TN, TR, UK, UP, WB };
